// ===== Drapeaux par pays — Dr. Stone Arena =====
// Couvre TOUS les pays du monde (noms français + variantes courantes).
// Le drapeau est généré à partir du code ISO 3166-1 alpha-2.
// Insensible à la casse et aux accents. Retourne 🌍 si non reconnu.

const ISO: Record<string, string> = {
  // ============ AFRIQUE (54 pays) ============
  'afrique du sud': 'ZA', 'south africa': 'ZA',
  'algerie': 'DZ', 'algeria': 'DZ',
  'angola': 'AO',
  'benin': 'BJ',
  'botswana': 'BW',
  'burkina faso': 'BF', 'burkina': 'BF',
  'burundi': 'BI',
  'cap vert': 'CV', 'cabo verde': 'CV',
  'cameroun': 'CM', 'cameroon': 'CM',
  'centrafrique': 'CF', 'republique centrafricaine': 'CF',
  'comores': 'KM',
  'congo': 'CG', 'congo brazzaville': 'CG', 'republique du congo': 'CG',
  'rd congo': 'CD', 'rdc': 'CD', 'congo kinshasa': 'CD', 'congo rdc': 'CD', 'republique democratique du congo': 'CD', 'drc': 'CD',
  'cote d ivoire': 'CI', "cote d'ivoire": 'CI', 'cote divoire': 'CI', 'ivoire': 'CI',
  'djibouti': 'DJ',
  'egypte': 'EG', 'egypt': 'EG',
  'erythree': 'ER', 'eritrea': 'ER',
  'eswatini': 'SZ', 'swaziland': 'SZ',
  'ethiopie': 'ET', 'ethiopia': 'ET',
  'gabon': 'GA',
  'gambie': 'GM', 'gambia': 'GM',
  'ghana': 'GH',
  'guinee': 'GN', 'guinea': 'GN',
  'guinee bissau': 'GW', 'guinee-bissau': 'GW', 'guinea bissau': 'GW',
  'guinee equatoriale': 'GQ', 'guinea equatorial': 'GQ',
  'kenya': 'KE',
  'lesotho': 'LS',
  'liberia': 'LR',
  'libye': 'LY', 'libya': 'LY',
  'madagascar': 'MG',
  'malawi': 'MW',
  'mali': 'ML',
  'maroc': 'MA', 'morocco': 'MA',
  'maurice': 'MU', 'iles maurice': 'MU', 'mauritius': 'MU',
  'mauritanie': 'MR',
  'mozambique': 'MZ',
  'namibie': 'NA', 'namibia': 'NA',
  'niger': 'NE',
  'nigeria': 'NG',
  'ouganda': 'UG', 'uganda': 'UG',
  'rwanda': 'RW',
  'sao tome et principe': 'ST', 'sao tome': 'ST', 'sao tome-et-principe': 'ST',
  'senegal': 'SN',
  'seychelles': 'SC',
  'sierra leone': 'SL',
  'somalie': 'SO', 'somalia': 'SO',
  'soudan': 'SD', 'sudan': 'SD',
  'soudan du sud': 'SS', 'south sudan': 'SS',
  'tanzanie': 'TZ', 'tanzania': 'TZ',
  'tchad': 'TD', 'chad': 'TD',
  'togo': 'TG',
  'tunisie': 'TN', 'tunisia': 'TN',
  'zambie': 'ZM', 'zambia': 'ZM',
  'zimbabwe': 'ZW',

  // ============ AMÉRIQUES (35 pays) ============
  'antigua et barbuda': 'AG', 'antigua': 'AG',
  'argentine': 'AR', 'argentina': 'AR',
  'bahamas': 'BS',
  'barbade': 'BB', 'barbados': 'BB',
  'belize': 'BZ',
  'bolivie': 'BO', 'bolivia': 'BO',
  'bresil': 'BR', 'brazil': 'BR',
  'canada': 'CA',
  'chili': 'CL', 'chile': 'CL',
  'colombie': 'CO', 'colombia': 'CO',
  'costa rica': 'CR',
  'cuba': 'CU',
  'dominique': 'DM',
  'equateur': 'EC', 'ecuador': 'EC',
  'etats unis': 'US', 'etats-unis': 'US', 'usa': 'US', 'united states': 'US', 'amerique': 'US',
  'grenade': 'GD', 'grenada': 'GD',
  'guatemala': 'GT',
  'guyana': 'GY',
  'haiti': 'HT',
  'honduras': 'HN',
  'jamaique': 'JM', 'jamaica': 'JM',
  'mexique': 'MX', 'mexico': 'MX',
  'nicaragua': 'NI',
  'panama': 'PA',
  'paraguay': 'PY',
  'perou': 'PE', 'peru': 'PE',
  'republique dominicaine': 'DO', 'dominican republic': 'DO',
  'saint kitts et nevis': 'KN', 'saint kitts': 'KN',
  'sainte lucie': 'LC', 'saint lucie': 'LC',
  'saint vincent et les grenadines': 'VC', 'saint vincent': 'VC',
  'salvador': 'SV', 'el salvador': 'SV',
  'suriname': 'SR', 'surinam': 'SR',
  'trinite et tobago': 'TT', 'trinidad and tobago': 'TT', 'trinite': 'TT',
  'uruguay': 'UY',
  'venezuela': 'VE',

  // ============ ASIE (48 pays) ============
  'afghanistan': 'AF',
  'arabie saoudite': 'SA', 'saudi arabia': 'SA', 'arabie': 'SA',
  'armenie': 'AM', 'armenia': 'AM',
  'azerbaidjan': 'AZ', 'azerbaijan': 'AZ',
  'bahrein': 'BH', 'bahrain': 'BH',
  'bangladesh': 'BD',
  'bhoutan': 'BT', 'bhutan': 'BT',
  'brunei': 'BN',
  'cambodge': 'KH',
  'chine': 'CN', 'china': 'CN',
  'chypre': 'CY', 'cyprus': 'CY',
  'coree du nord': 'KP', 'coree du nord korea': 'KP', 'north korea': 'KP',
  'coree du sud': 'KR', 'coree': 'KR', 'south korea': 'KR', 'korea': 'KR',
  'emirats arabes unis': 'AE', 'emirats': 'AE', 'uae': 'AE', 'united arab emirates': 'AE',
  'georgie': 'GE', 'georgia': 'GE',
  'inde': 'IN', 'india': 'IN',
  'indonesie': 'ID', 'indonesia': 'ID',
  'irak': 'IQ', 'iraq': 'IQ',
  'iran': 'IR',
  'israel': 'IL',
  'japon': 'JP', 'japan': 'JP',
  'jordanie': 'JO', 'jordan': 'JO',
  'kazakhstan': 'KZ',
  'kirghizistan': 'KG',
  'koweit': 'KW', 'kuwait': 'KW',
  'laos': 'LA',
  'liban': 'LB', 'lebanon': 'LB',
  'malaisie': 'MY', 'malaysia': 'MY',
  'maldives': 'MV',
  'mongolie': 'MN', 'mongolia': 'MN',
  'myanmar': 'MM', 'burma': 'MM',
  'nepal': 'NP',
  'oman': 'OM',
  'ouzbekistan': 'UZ',
  'pakistan': 'PK',
  'palestine': 'PS',
  'philippines': 'PH',
  'qatar': 'QA',
  'russie': 'RU', 'russia': 'RU', 'russian federation': 'RU',
  'singapour': 'SG', 'singapore': 'SG',
  'sri lanka': 'LK',
  'syrie': 'SY', 'syria': 'SY',
  'tadjikistan': 'TJ',
  'thailande': 'TH', 'thailand': 'TH',
  'timor oriental': 'TL', 'timor': 'TL', 'east timor': 'TL',
  'turkmenistan': 'TM',
  'turquie': 'TR', 'turkey': 'TR', 'turkiye': 'TR',
  'viet nam': 'VN', 'vietnam': 'VN',

  // ============ EUROPE (44+ pays) ============
  'albanie': 'AL', 'albania': 'AL',
  'allemagne': 'DE', 'germany': 'DE',
  'andorre': 'AD', 'andorra': 'AD',
  'autriche': 'AT', 'austria': 'AT',
  'bielorussie': 'BY', 'belarus': 'BY',
  'belgique': 'BE', 'belgium': 'BE',
  'bosnie herzegovine': 'BA', 'bosnie': 'BA', 'bosnia and herzegovina': 'BA',
  'bulgarie': 'BG', 'bulgaria': 'BG',
  'croatie': 'HR', 'croatia': 'HR',
  'danemark': 'DK', 'denmark': 'DK',
  'espagne': 'ES', 'spain': 'ES',
  'estonie': 'EE', 'estonia': 'EE',
  'finlande': 'FI', 'finland': 'FI',
  'france': 'FR',
  'grece': 'GR', 'greece': 'GR',
  'hongrie': 'HU', 'hungary': 'HU',
  'irlande': 'IE', 'ireland': 'IE',
  'islande': 'IS', 'iceland': 'IS',
  'italie': 'IT', 'italy': 'IT',
  'lettonie': 'LV', 'latvia': 'LV',
  'liechtenstein': 'LI',
  'lituanie': 'LT', 'lithuania': 'LT',
  'luxembourg': 'LU',
  'macedoine du nord': 'MK', 'macedoine': 'MK', 'north macedonia': 'MK',
  'malte': 'MT', 'malta': 'MT',
  'moldavie': 'MD', 'moldova': 'MD',
  'monaco': 'MC',
  'montenegro': 'ME',
  'norvege': 'NO', 'norway': 'NO',
  'pays bas': 'NL', 'pays-bas': 'NL', 'hollande': 'NL', 'netherlands': 'NL',
  'pologne': 'PL', 'poland': 'PL',
  'portugal': 'PT',
  'roumanie': 'RO', 'romania': 'RO',
  'royaume uni': 'GB', 'royaume-uni': 'GB', 'uk': 'GB', 'united kingdom': 'GB', 'grande bretagne': 'GB', 'angleterre': 'GB', 'england': 'GB',
  'saint marin': 'SM', 'san marino': 'SM',
  'serbie': 'RS', 'serbia': 'RS',
  'slovaquie': 'SK', 'slovakia': 'SK',
  'slovenie': 'SI', 'slovenia': 'SI',
  'suede': 'SE', 'sweden': 'SE',
  'suisse': 'CH', 'switzerland': 'CH',
  'tchequie': 'CZ', 'republique tcheque': 'CZ', 'czech republic': 'CZ', 'czechia': 'CZ',
  'ukraine': 'UA',
  'vatican': 'VA',

  // ============ OCÉANIE (14 pays) ============
  'australie': 'AU', 'australia': 'AU',
  'fidji': 'FJ', 'fiji': 'FJ',
  'kiribati': 'KI',
  'iles marshall': 'MH', 'marshall islands': 'MH',
  'micronesie': 'FM', 'micronesia': 'FM',
  'nauru': 'NR',
  'nouvelle zelande': 'NZ', 'new zealand': 'NZ',
  'pala': 'PW', 'palau': 'PW',
  'papouasie nouvelle guinee': 'PG', 'papouasie': 'PG', 'papua new guinea': 'PG',
  'samoa': 'WS',
  'iles salomon': 'SB', 'solomon islands': 'SB',
  'tonga': 'TO',
  'tuvalu': 'TV',
  'vanuatu': 'VU',

   // ============ AUTRES TERRITOIRES COURANTS ============
  'taiwan': 'TW',
  'hong kong': 'HK',
};

// Convertit un code ISO 2 lettres en emoji drapeau (règle Unicode "regional indicators")
function isoToFlag(iso: string): string {
  return String.fromCodePoint(
    0x1F1E6 + (iso.charCodeAt(0) - 65),
    0x1F1E6 + (iso.charCodeAt(1) - 65)
  );
}

export function getCountryFlag(pays: string | null | undefined): string {
  if (!pays) return '🌍';
  const key = pays
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // retire les accents (é → e)
    .replace(/\s+/g, ' '); // espaces multiples → un seul
  const iso = ISO[key];
  return iso ? isoToFlag(iso) : '🌍';
}